### ISSUE TITLE
Not working on 3.2

### ISSUE THREAD

**Issue by meis2m** [alg5/addonforthanksforposts#15]
Hello
i install that and it seems not working yet on 3.2

**Comment by Galixte** [comment]
Hi @Persian-phpBB,

add more details about your issue.

@rxu, could you take a look, please ?

**Comment by alg5** [comment]
Hi @Persian-phpBB , take it from branch dev_3.2.x

**Comment by rxu** [comment]
@alg5 Making the 3.2 branch default can save you from a lot of headaches 😉

**Comment by Galixte** [comment]
@Persian-phpBB direct download link: https://github.com/alg5/addonforthanksforposts/archive/dev_3.2.x.zip

**Comment by alg5** [comment]
@rxu , done :)

**Comment by Persian-phpBB** [comment]
it is still not working :(

**Comment by alg5** [comment]
What is the style you are using?
Did you see any errors in firebug?

**Comment by alg5** [comment]
not  answer and not activities during last year
