### ISSUE TITLE
The selected extension cannot be enabled, please verify the extension’s requirements.

### ISSUE THREAD

**Issue by meis2m** [alg5/addonforthanksforposts#17]
Hello
what this error ?

The selected extension cannot be enabled, please verify the extension’s requirements. i am using 3.0.6

**Comment by alg5** [comment]
the addon's requirements - ThanksForPosts extension (https://github.com/rxu/thanks_for_posts) should be installed and activated before

**Comment by mahdi1944** [comment]
Hi,
I changed return $phpbb_extension_manager->is_enabled('gfksx/thanksforposts'); to return $phpbb_extension_manager->is_enabled('gfksx/ThanksForPosts'); and installed on phpbb3.3.2, but not working
can you help me?
