### ISSUE TITLE
Complete integration with Hide BBcode ext

### ISSUE THREAD

**Issue by roiebh** [alg5/addonforthanksforposts#22]
When using this addon the hidden text is not shown because there is no refresh to the page.
Do you think you'll be able to add this feature to work smoothly with the BBcode [hide]:
https://github.com/marcovo/phpbb_hidebbcode

Thank you

**Comment by alg5** [comment]
Hi @roiebh I don't understand this problem. I see hidden text after like and dislike

**Comment by roiebh** [comment]
Usually when you click "like" the page refresh and the hidden text becomes unhidden.
With this Add-on the text stays hidden.

**Comment by alg5** [comment]
ok. I understood I'll try to fix it

**Comment by roiebh** [comment]
Thank you so much

**Comment by alg5** [comment]
please, use version 3.0.10

**Comment by roiebh** [comment]
Works perfectly! Thank you so much!
